/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Jellepostma (https://sketchfab.com/Jellepostma)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/japanese-restaurant-inakaya-97594e92c418491ab7f032ed2abbf596
Title: Japanese Restaurant "Inakaya"
*/

import React, { useRef, useEffect } from 'react'
import { useFrame, useThree } from '@react-three/fiber';
import { useGLTF } from '@react-three/drei'
import { a } from '@react-spring/three';

import japanScene from '../assets/3d/japanese_restaurant_inakaya.glb'

const Japan = (props) => {
  const japanRef = useRef();

  const { nodes, materials } = useGLTF(japanScene);

  return (
    <a.group ref={japanRef} {...props} >
            <group rotation={[-Math.PI / 2, 0, 1.5]} scale={.0105}>
        <group rotation={[Math.PI / 2, 1, 0]}>
          <group
            position={[248.516, 848.858, 1044.06]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Inakaya_Inakaya_final_0.geometry}
              material={materials.Inakaya_final}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Inakaya_Inakaya_final_0_1.geometry}
              material={materials.Inakaya_final}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Inakaya_Decals_0.geometry}
              material={materials.Decals}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Inakaya_Glass_0.geometry}
              material={materials.Glass}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Inakaya_II_Lamp_0.geometry}
              material={materials.II_Lamp}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Inakaya_Alphas_D_0.geometry}
              material={materials.Alphas_D}
            />
          </group>
        </group>
      </group>
    </a.group>
  )
}


export default Japan;